stages:
  - test

test:
  image: node:12-alpine
  stage: test
  script:
    - npm install
    - ng test
  only:
    - master
  cache:
    key:
      files:
        -package-lock.json
  paths:
    - node_modules