name: main
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  Testing:
    name: Run npm install & test
    runs-on: ubuntu-latest
    steps:
      - name: npm install
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: angular testing
      - run: npm run test-ci