name: main
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  Testing:
    name: Run npm install & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm ci
        run: npm ci
      - name: angular testing
        run: npm run test-ci