name: main
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  Testing:
    name: Run npm install & test
    runs-on: ubuntu-latest
    steps:
      - name: npm install
      - run: npm install
      - name: angular testing
      - run: npm run test-ci