# Based on https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install
        run: npm instal
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:ci
